apiVersion: v1
kind: Namespace
metadata:
  name: sih-health-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions
  namespace: sih-health-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions
  template:
    metadata:
      labels:
        app: actions
    spec:
      containers:
        - name: actions
          image: actions:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/sih_health_bot
            - name: REDIS_URL
              value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: actions
  namespace: sih-health-bot
spec:
  selector:
    app: actions
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
  namespace: sih-health-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      containers:
        - name: rasa
          image: rasa:latest
          ports:
            - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: rasa
  namespace: sih-health-bot
spec:
  selector:
    app: rasa
  ports:
    - port: 5005
      targetPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: sih-health-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: sih-health-bot
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080













